/**:
  ros__parameters:
    moveit_servo:
      publish_period: 0.0333
      use_gazebo: false
      command_in_type: "unitless"
      linear_scale:  0.2
      rotational_scale: 0.5
      joint_scale: 0.1
      cartesian_command_in_topic: ~/delta_twist_cmds
      joint_command_in_topic: ~/delta_joint_cmds
      command_out_topic: /gp4_arm_controller/joint_trajectory
      command_out_type: trajectory_msgs/JointTrajectory
      check_collisions: true
      collision_check_rate: 10.0
      self_collision_proximity_threshold: 0.01
      scene_collision_proximity_threshold: 0.02
      move_group_name: gp4_arm
      planning_frame: base_link
      ee_frame_name: tool0
      lower_singularity_threshold:  17.0
      hard_stop_singularity_threshold: 30.0
      joint_limit_margin: 0.1
